### PR TITLE
created setup file

### LINKED ISSUE #14: Add a setup so that the app can be installed

### PR DESCRIPTION
**Pull request by northwestwitch**
Fix #14

### CODE REVIEW

**Comment by emmser** [comment]
Shall this branch be used? Or is connection_draft the one to use?

**Comment by northwestwitch** [comment]
If you are working on the connections use the connection_draft!

**Comment by northwestwitch** [comment]
Do you want me to fix the connection adapter so you can start working on
the CLI?

**Comment by emmser** [comment]
@northwestwitch  that would be great!

**Pull request merged**
